import { AuthWrapper } from '@/shared';

import './global.css';

export const metadata = {
  description: 'Generated by create-nx-workspace',
  title: 'Welcome to bleksi',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthWrapper>
          <div className="w-screen h-screen bg-slate-400 flex items-center justify-center">
            {children}
          </div>
        </AuthWrapper>
      </body>
    </html>
  );
}
